### PR TITLE
df-91->Implement Filtered Querying 

### PR DESCRIPTION
**Pull request by vijaypoojari**
This PR includes:

- converting the raw XML to JSON Object.
- making the REST call to get the populated JSON
- comparing the JSON objects and creating a JSON Object out of populated fields.
- converting JSON Object back to WITSML Object back to XML.

This connects to #91

### CODE REVIEW

**Comment by randypitcherii** [comment]
@vijaypoojari Please merge from master.

In the future, please do not submit PR's before you've merged master into your branch

**Comment by randypitcherii** [comment]
Please ensure that your code packages successfully locally before creating a PR. A huge number of tests are failing in TRAVIS that should also be failing locally for you.

**Comment by vijaypoojari** [comment]
I have shifted all logic from StoreImpl to Valve.

**Comment by vijaypoojari** [comment]
@cherrera2001 @randypitcherii as there was issue in this ticket of the methods that were already present. please mention in the feature tickets regarding the existing classes and methods that I have to use, if any.

**Pull request closed without merging**
